[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[project]
name = "rllib_lagrange_ppo"
authors = [{name = "Aivar Sootla"}]
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.7, <=3.10"
dependencies = ["gym[accept-rom-license]", "gymnasium[accept-rom-license, atari]==0.28.1", "ray[rllib]==2.7.0"]

[project.optional-dependencies]
development = ["pytest>=7.2.2", "torch==1.13.1"]
